name: PR Storybook Preview
on: pull_request_target

jobs:
  deploy-pr-preview:
    name: Deploy to Surge
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn install
      - name: Build Storybook
        run: yarn storybook:export
      - name: Generate Surge URL
        uses: actions/github-script@v3
        id: surge-url
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { issue: { number: issue_number } } = context;
            return `konveyor-lib-ui-pr-${issue_number}-preview.surge.sh`;
          result-encoding: string
      - name: Install Surge
        run: npm install -g surge
      - name: Deploy Storybook to Surge
        run: surge ./storybook-static/ "${{steps.surge-url.outputs.result}}" --token ${{ secrets.SURGE_TOKEN }}
      - name: Post URL as PR comment
        uses: mshick/add-pr-comment@v1
        with:
          message: "✨ Deployed Storybook Preview: http://${{steps.surge-url.outputs.result}}"
          repo-token: ${{ secrets.GH_TOKEN }}
